// AUTOGENERATED - DO NOT EDIT

package tdlib

type UserNames struct{
	ActiveUsernames   []string  `json:"active_usernames"`
	DisabledUsernames []string  `json:"disabled_usernames"`
	EditableUsername  string    `json:"editable_username"`
}